app/gui/views.py
import os
from flask import Blueprint, request, render_template, flash, send_file, current_app
from werkzeug.exceptions import HTTPException
from app.api import functionality as api_func
import utilities.custom_app_logger as cust_log
# from app.constants import FileSystemInformation as fsi

bp_gui = Blueprint(
    'bp_gui'
    , __name__
    , url_prefix='/gui'
    , template_folder='templates'
    , static_folder=os.path.join(os.path.dirname(__file__), 'static')
    , static_url_path='/bp_gui/static'
)


@bp_gui.route('/', methods=['GET'])
@bp_gui.route('/home', methods=['GET'])
def index():
    return_data_extract = api_func.return_all_mapping_information(return_json_response=False)
    cust_log.log_message(level='info', message='Calling endpoint /gui', call_type='GUI')
    return render_template('index.html', display_data_extract=return_data_extract)


@bp_gui.route('/release', methods=['GET'])
def release():
    cust_log.log_message(level='info', message='Calling endpoint /gui/release', call_type='GUI')
    return render_template('release.html')


# @bp_gui.route('/file/template', methods=['GET', 'POST'])
# def template_file():
#     template_path = fr'{os.path.join(current_app.root_path, fsi.DATA_TEMPLATE_FOLDER)}\{fsi.DATA_TEMPLATE_FILENAME}'
#     print(template_path)
#     cust_log.log_message(level='info', message='Calling endpoint /gui/file/template - Downloading template', call_type='GUI')
#     return send_file(path_or_file=template_path, as_attachment=True)


@bp_gui.route('/admin', methods=['GET'])
def admin():
    if request.args.get('download') == 'true':
        flash('Template downloaded successfully!', 'success')
        
    return_data_extract = api_func.return_all_mapping_information(return_json_response=False)
    cust_log.log_message(level='info', message='Calling endpoint /gui/admin', call_type='GUI')
    return render_template('admin.html', display_data_extract=return_data_extract)


@bp_gui.errorhandler(HTTPException)
def display_error_page_404(error):
    error_short_description = "Something went wrong"
    error_message = error.description
    return render_template('error.html', error_short_desc=error_short_description, error_message=error_message), 404

app/gui/templates/admin.html
{% extends 'layout.html' %}

{% block title %} Admin {% endblock %}
{% block role %} Admin {% endblock %}

{% block content %}

<section class="button-container">
    <div class="button-group">
        <div class="title">Data Actions</div>
        <div>
            <!-- <button class="button" id="add-button">Add Row</button>
            <button class="button" id="delete-button">Delete Row</button> -->
            <button class="button" id="import-button">Import File</button>
            <button class="button" id="export-button">Export File</button>
            <a class="button" id="export-button" href="{{ url_for('bp_gui.template_file') }}">Download Template</a>
        </div>
    </div>
    <div class="button-group">
        <div class="title">Release Action</div>
        <div>
            <button class="button" id="add-button">New Release Note</button>
            <button class="button" id="delete-button">Update Release Note</button>
        </div>
    </div>
</section>

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
        <li class="alert alert-{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endwith %}


{% endblock %}

app/gui/templates/error.html
{% extends 'layout.html' %}

{% block content %}

<section class="error_container">
    <div class="error_header">
        <div class="error_code">{{ error_short_desc }}</div>
    </div>
    <div class="error_content">
        <p>{{ error_message }}</p>
        <p>We recommend trying again later. If the problem persists, feel free to report it to our support team at 'service.email@gmail.com'.</p>
        <div class="button_container">
            <a href="{{ url_for('bp_gui.index') }}" class="back_button">Go back to the homepage</a>
            <a href="mailto:deepraj.developer@gmail.com" class="report back_button">Report the issue</a>
        </div>
    </div>
</section>

{% endblock %}

app/gui/templates/index.html
{% extends 'layout.html' %}

{% block title %} Home {% endblock %}
{% block role %} Developer {% endblock %}

{% block content %}

<section class="search_container">
    <input type="search" name="search" id="search" placeholder="Search Anything ..." class="search_input" required>
    <button type="submit" class="search_button" id="search_button">🔍 SEARCH</button>
    <button type="submit" class="clear_button" id="clear_button">🗑️ CLEAR</button>
</section>

<section class="content-container">
    <table class="content-table" id="content-table">
        <thead>
            <tr>
                <th colspan="1" class="no-class" id="sticky-column"></th>
                <th colspan="7" class="api-class">API INFROMATION</th>
                <th colspan="3" class="flag-class">FLAGS</th>
                <th colspan="7" class="gui-class">GUI INFORMATION</th>
                <!-- <th colspan="1" class="db-class"></th> -->
            </tr>
            <tr>
                <th class="no-class" id="sticky-column">ID</th>

                <th class="api-class">Entity Name</th>
                <th class="api-class">Domain Name</th>
                <th class="api-class">Subdomain Name</th>
                <th class="api-class">Child Domain Name (Lvl-1)</th>
                <th class="api-class">Child Domain name (Lvl-2)</th>
                <th class="api-class">Business Field Name</th>
                <th class="api-class">Type</th>
                
                <th class="flag-class">Read API</th>
                <th class="flag-class">Write API</th>
                <th class="flag-class">Kafka Msg</th>

                <th class="gui-class">Screen Name</th>
                <th class="gui-class">Section Name</th>
                <th class="gui-class">Label Name</th>
                <th class="gui-class">Label Description</th>
                <th class="gui-class">Field State</th>
                <th class="gui-class">Field Type</th>
                <th class="gui-class">Dependent on</th>

                <!-- <th class="db-class">DATABASE INFORMATION</th> -->
            </tr>
        </thead>
        <tbody>
            {% for display_item in display_data_extract %}
            <tr>
                <td class="no-class" id="sticky-column">{{ display_item['guiFieldIdentifier'] }}</td>
                <!-- API Information Fields -->
                <td>{{ display_item['apiInformation']['entityName'] }}</td>
                <td>{{ display_item['apiInformation']['domainName'] }}</td>
                <td>{{ display_item['apiInformation']['subdomainName'] }}</td>
                <td>{{ display_item['apiInformation']['childDomainNameLvl1'] }}</td>
                <td>{{ display_item['apiInformation']['childDomainNameLvl2'] }}</td>
                <td>{{ display_item['apiInformation']['businessFieldName'] }}</td>
                <td>{{ display_item['apiInformation']['type'] }}</td>
                <!-- API Flags Information -->
                <td>{{ display_item['apiExposureFlags']['readAPI'] }}</td>
                <td>{{ display_item['apiExposureFlags']['writeAPI'] }}</td>
                <td>{{ display_item['apiExposureFlags']['kafka'] }}</td>
                <!-- GUI Information Fields -->
                <td>{{ display_item['guiInformation']['screenName'] }}</td>
                <td>{{ display_item['guiInformation']['sectionName'] }}</td>
                <td>{{ display_item['guiInformation']['fieldName'] }}</td>
                <td>{{ display_item['guiInformation']['fieldDescription'] }}</td>
                <td>{{ display_item['guiInformation']['fieldState'] }}</td>
                <td>{{ display_item['guiInformation']['fieldType'] }}</td>
                <td>{{ display_item['guiInformation']['fieldDependencyId'] }}</td>
                <!-- Database Information Fields -->
                <!-- <td>
                    <table class="db-table">
                        <thead>
                            <th class="db-class">Table Name</th>
                            <th class="db-class">Column Name</th>
                            <th class="db-class">Column Size</th>
                            <th class="db-class">Datatype</th>
                        </thead>
                        <tbody>
                            {% for db_info in display_item['databaseInformation'] %}
                            <tr>
                                <td>{{ db_info['tableName'] }}</td>
                                <td>{{ db_info['columnName'] }}</td>
                                <td>{{ db_info['columnSize'] }}</td>
                                <td>{{ db_info['dataType'] }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td> -->
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

<section id="pagination-container"></section>

{% endblock %}

app/gui/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UFMA | {% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('bp_gui.static', filename='styleSheets/css/main.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Imprima&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('bp_gui.static', filename='images/favicon.png') }}" type="image/x-icon">
</head>
<body> 
    <section class="navbar-container">
        <a href="{{ url_for('bp_gui.index') }}" class="navbar-title">
            <img src="{{ url_for('bp_gui.static', filename='images/favicon.png') }}" alt="" srcset="" class="navbar-logo">
            Unified Field Mapping Assistant
        </a>
        <div class="navbar-button-container">
            <div class="role-info"><b>Role:</b> {% block role %}{% endblock %}</div>

            <a class="button" href="{{ url_for('bp_gui.release') }}">Release Notes</a>
            <a class="admin" href="{{ url_for('bp_gui.admin') }}">Admin</a>
        </div>
    </section>
    
    {% block content %}{% endblock %}    

    <script src="{{ url_for('bp_gui.static', filename='javascript/main.js') }}"></script>
</body>
</html>

app/gui/templates/release.html
{% extends 'layout.html' %}

{% block title %} Release Notes {% endblock %}

{% block content %}


<section class="release-container">
    <div class="release-card">
        <div class="card-title">
            <div class="tags">
                <p class="version-new">LATEST</p>
                <p class="version-date">May 09, 2025</p>
            </div>
            <p class="version-name">Version 1.0.0</p>
        </div>
        <div class="items">
            <span class="enhn">Major update with performance improvements and UI enhancements.</span>
        </div>
    </div>    
    
</section>

{% endblock %}